spring.application.name=notification-service
server.port=8085
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=Ashish
spring.rabbitmq.password=9ki8nrjjis
management.endpoints.web.exposure.include=health


spring.datasource.username=jewellery
spring.datasource.password=Ashish@10

spring.datasource.password=9ki8nrjjis
